version: '3.4'

services:
  postgres:
    container_name: rest-db
    image: postgres
    ports:
      - 5432:5432
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mainuser
      POSTGRES_DB: restapi
      POSTGRES_PASSWORD: restapi

volumes:
  postgres_data: